'use client';
import{useEffect,useMemo,useState}from'react';import{useParams,useRouter,useSearchParams}from'next/navigation';import Link from'next/link';import{AppShell}from'@/src/components/AppShell';import{applyDiscount,naira,serviceFee}from'@/src/lib/app-config';

export default function Fund(){
 const{id}=useParams<{id:string}>(),router=useRouter(),q=useSearchParams();const[t,setT]=useState<any>(null),[bank,setBank]=useState(0),[wallet,setWallet]=useState(0),[discount,setDiscount]=useState(0),[pin,setPin]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[handoffPin,setHandoffPin]=useState('');
 useEffect(()=>{Promise.all([fetch('/api/tasks/'+id).then(r=>r.json()),fetch('/api/me').then(r=>r.json())]).then(([x,m])=>{setT(x.task);setBank(Number(m.streak?.discount_percent||0));setWallet(Number(m.wallet?.available_kobo||0))})},[id]);
 const calc=useMemo(()=>{const a=Array.isArray(t?.agreement)?t.agreement[0]:t?.agreement;const item=Number(a?.item_budget_kobo||0),runner=Number(a?.runner_fee_kobo||0),base=serviceFee(Math.max(0,runner-Number(t?.same_gender_premium_kobo||0))),after=applyDiscount(base,discount);return{item,runner,base,after,total:item+runner+after}},[t,discount]);
 const topup= q.get('topup')==='1';
 async function fund(){setBusy(true);setErr('');const r=topup?await fetch('/api/tasks/'+id+'/price-adjustment',{method:'GET'}):null;
  if(topup){const j=await r!.json();const adj=(j.adjustments||[]).find((x:any)=>x.status==='APPROVED');if(!adj){setBusy(false);setErr('Approved adjustment not found.');return}const f=await fetch('/api/tasks/'+id+'/price-adjustment/fund',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({adjustment_id:adj.id})});const fj=await f.json();setBusy(false);if(!f.ok){setErr(fj.error||'Could not fund the top-up.');return}router.push('/orders/'+id);return}
  const r=await fetch('/api/tasks/'+id+'/fund',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({discount_percent:discount,handoff_pin:pin})});const j=await r.json();setBusy(false);if(!r.ok){setErr(j.error||'Could not fund task.');return}const hp=await fetch('/api/tasks/'+id+'/handoff',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'rotate'})});const hj=await hp.json();setHandoffPin(hj.pin||'');setDone(true)}
 async function addMoney(){const amount=prompt('Add money to wallet (₦). Minimum ₦100.');if(!amount)return;const r=await fetch('/api/wallet/topup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount_kobo:Math.round(Number(amount)*100)})});const j=await r.json();if(!r.ok){setErr(j.error||'Could not start top-up.');return}location.href=j.authorization_url}
 if(!t)return <AppShell><main className="shell app-page"><div className="card form"><h2>Loading funding…</h2></div></main></AppShell>;
 if(done)return <AppShell><main className="shell app-page narrow"><div className="card success"><div className="success-icon">✓</div><div className="eyebrow">FUNDED</div><h2>Money is locked. The runner can go.</h2><p className="sub">Keep this handoff code private. Give it to the runner only when the delivery reaches you.</p><div className="pin-display"><small>HANDOFF CODE</small><strong>{handoffPin}</strong></div><div className="actions"><Link className="btn dark" href={'/orders/'+id}>Open task</Link><Link className="btn ghost" href="/orders">Orders</Link></div></div></main></AppShell>;
 const balanceReady=!topup&&wallet>=calc.total;
 return <AppShell><main className="shell app-page narrow"><div className="page-top"><div><div className="eyebrow">{topup?'TOP-UP':'FUND TASK'}</div><h1 className="app-title">{topup?'Close the price gap.':'Lock it. Then go.'}</h1><p className="sub">{topup?'The runner can continue once the approved item-price increase is funded.':'Funding moves the agreed item capital and runner compensation into escrow before execution.'}</p></div></div><div className="card form">
  <div className="review"><b>{t.title}</b><span>{t.pickup_location_text} → {t.destination_location_text}</span>{!topup&&<><span>Item capital · {naira(calc.item)}</span><span>Runner compensation · {naira(calc.runner)}</span><span>CarryGo fee · {naira(calc.base)} → {naira(calc.after)}</span></>}</div>
  {!topup&&<><label>Streak discount · {bank}% available<div className="discount-line"><input type="range" min="0" max={bank} step="5" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/><b>{discount}%</b></div><small className="hint">{bank-discount}% remains banked. You can spend it later.</small></label><label>Handoff PIN<div className="grid2"><input className="pin-box" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6 digits"/><div className="soft-note">Only the person receiving the delivery should know this code.</div></div></label><div className="balance-line"><span>Wallet available</span><b>{naira(wallet)}</b></div><div className="total"><small>Total needed</small><b>{naira(calc.total)}</b></div>{wallet<calc.total&&<button type="button" className="btn ghost full" onClick={addMoney}>Add money to wallet →</button>}</>}
  {topup&&<><div className="soft-note">Only the approved variance is funded here. Your original escrow stays locked and unchanged.</div><div className="balance-line"><span>Wallet available</span><b>{naira(wallet)}</b></div></>}
  {err&&<div className="error">{err}</div>}<button className="btn dark full" disabled={busy||(topup?wallet<=0:!balanceReady||pin.length!==6)} onClick={fund}>{busy?'Securing funds…':topup?'Fund approved increase':'Fund from wallet →'}</button>
 </div></main></AppShell>
}
