'use client';

import{useEffect,useMemo,useState}from'react';import{useParams}from'next/navigation';import Link from'next/link';import{AppShell}from'@/src/components/AppShell';import{applyDiscount,naira,serviceFee}from'@/src/lib/app-config';

export default function Fund(){
 const{id}=useParams<{id:string}>();const[t,setT]=useState<any>(null),[bank,setBank]=useState(0),[wallet,setWallet]=useState(0),[discount,setDiscount]=useState(0),[pin,setPin]=useState(''),[topup,setTopup]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[handoffPin,setHandoffPin]=useState('');
 useEffect(()=>{Promise.all([fetch('/api/tasks/'+id).then(r=>r.json()),fetch('/api/me').then(r=>r.json())]).then(([x,m])=>{if(!x?.task)throw new Error(x?.error||'Could not load task.');setT(x.task);setBank(Number(m.streak?.discount_percent||0));setWallet(Number(m.wallet?.available_kobo||0))}).catch(e=>setError(e instanceof Error?e.message:'Could not load funding details.'))},[id]);
 const calc=useMemo(()=>{const a=Array.isArray(t?.agreement)?t.agreement[0]:t?.agreement;const item=Number(a?.item_budget_kobo||0),runner=Number(a?.runner_fee_kobo||0),premium=Number(t?.same_gender_premium_kobo||0),base=serviceFee(Math.max(0,runner-premium)),after=applyDiscount(base,discount);return{item,runner,premium,base,after,total:item+runner+after}},[t,discount]);
 async function fund(){setBusy(true);setError('');const r=await fetch('/api/tasks/'+id+'/fund',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({discount_percent:discount,handoff_pin:pin})}),j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Could not fund task.');return}setHandoffPin(pin);setDone(true);}
 async function addMoney(){const amount=Math.round(Number(topup||0)*100);if(!Number.isFinite(amount)||amount<10000){setError('Top up at least ₦100.');return}setBusy(true);setError('');const r=await fetch('/api/wallet/topup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount_kobo:amount})}),j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Could not start top-up.');return}window.location.assign(j.authorization_url);}
 if(!t)return <AppShell><main className="shell app-page"><div className="card form"><h2>Loading funding…</h2></div></main></AppShell>;
 if(done)return <AppShell><main className="shell app-page narrow"><div className="card success"><div className="eyebrow">FUNDED</div><h2>Money is locked.</h2><p className="sub">Your handoff code is saved on this device only in this screen. Keep it private and give it to the runner at the handoff.</p><div className="pin-display"><small>HANDOFF CODE</small><strong>{handoffPin}</strong></div><div className="actions"><Link className="btn dark" href={'/orders/'+id}>Open task</Link><Link className="btn ghost" href="/orders">Orders</Link></div></div></main></AppShell>;
 const shortfall=Math.max(0,calc.total-wallet),ready=wallet>=calc.total&&pin.length===6;
 return <AppShell><main className="shell app-page narrow"><div className="page-top"><div><div className="eyebrow">FUND TASK</div><h1 className="app-title">Lock it. <em>Then go.</em></h1><p className="sub">The agreed amount is reserved before execution. Your streak can reduce the CarryGo fee.</p></div></div><div className="card form"><div className="review"><b>{t.title}</b><span>{t.pickup_location_text} → {t.destination_location_text}{t.delivery_mode==='ROOM'?' · same-gender room '+t.delivery_room:''}</span><span>Item capital · {naira(calc.item)}</span><span>Runner compensation · {naira(calc.runner)}</span><span>Room premium · {calc.premium?naira(calc.premium):'—'}</span><span>CarryGo fee · {naira(calc.base)} → {naira(calc.after)}</span></div><label>Streak discount · {bank}% banked<div className="discount-line"><input aria-label="Streak discount percentage" type="range" min="0" max={bank} step="5" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/><b>{discount}%</b></div><small className="hint">{bank-discount}% remains banked. Use any portion now.</small></label><label>Handoff PIN<div className="grid2"><input aria-label="Six digit handoff PIN" className="pin-box" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6 digits"/><div className="soft-note">You choose this code. The runner should only receive it when the delivery is in your hands.</div></div></label><div className="balance-line"><span>Wallet available</span><b>{naira(wallet)}</b></div><div className="total"><small>Total needed</small><b>{naira(calc.total)}</b></div>{wallet<calc.total&&<div className="topup-inline"><label>Top up enough to fund<div className="grid2"><input inputMode="numeric" value={topup} onChange={e=>setTopup(e.target.value.replace(/\D/g,''))} placeholder={String(Math.ceil((calc.total-wallet)/100))}/><span className="soft-note">Need about {naira(shortfall)} more.</span></div></label><button type="button" className="btn ghost full" disabled={busy||!topup} onClick={addMoney}>Continue to Paystack →</button></div>}{error&&<div className="error" role="alert">{error}</div>}<button className="btn dark full" disabled={busy||!ready} onClick={fund}>{busy?'Securing funds…':'Fund from wallet →'}</button></div></main></AppShell>;
}