'use client';
import{useEffect,useState}from'react';import Link from'next/link';import{AppShell}from'@/src/components/AppShell';import{naira}from'@/src/lib/app-config';

export default function Earn(){
 const[tasks,setTasks]=useState<any[]>([]),[login,setLogin]=useState(false),[selected,setSelected]=useState<any|null>(null),[fee,setFee]=useState(''),[eta,setEta]=useState('20'),[float,setFloat]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!selected)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setSelected(null);return}if(e.key!=='Tab')return;const dialog=document.getElementById('offer-dialog');if(!dialog)return;const focusable=Array.from(dialog.querySelectorAll<HTMLElement>('button,input,textarea,select,[href],[tabindex]:not([tabindex="-1"])')).filter(el=>!el.hasAttribute('disabled'));if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};window.addEventListener('keydown',onKey);queueMicrotask(()=>document.getElementById('offer-dialog')?.querySelector<HTMLElement>('input,button')?.focus());return()=>window.removeEventListener('keydown',onKey)},[selected]);
 useEffect(()=>{fetch('/api/tasks').then(async r=>{if(r.status===401){setLogin(true);return}const j=await r.json();setTasks(j.tasks||[])}).catch(()=>setError('Weak connection. Try again.'))},[]);
 async function offer(){if(!selected)return;setBusy(true);const r=await fetch('/api/tasks/'+selected.id+'/bids',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fee_kobo:Math.round(Number(fee||0)*100),eta_minutes:Number(eta||20),runner_float_capacity_kobo:Math.round(Number(float||0)*100),message})});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Could not send offer.');return}setSelected(null);setTasks(x=>x.filter(t=>t.id!==selected.id));setMessage('') }
 if(login)return <AppShell><main className="shell app-page narrow"><div className="card success"><h2>Earn from the routes you already take.</h2><p className="sub">Sign in to bid and build your reliability history.</p><Link className="btn dark" href="/login">Sign in →</Link></div></main></AppShell>;

 return <AppShell><main className="shell app-page"><div className="page-top"><div><div className="eyebrow">RUNNER MODE</div><h1 className="app-title">What can you <em>carry?</em></h1><p className="sub">See the request, set your fee, set your ETA, send.</p></div><span className="open-state">LIVE</span></div>{error&&<div className="error">{error}</div>}<div className="filter-strip" aria-label="Task filters"><button type="button" className="filter active">All tasks</button><button type="button" className="filter">Room eligible</button><button type="button" className="filter">Lower capital</button></div><div className="task-list">{tasks.map(t=><article className="runner-card card" key={t.id}><div className="runner-main"><div className="task-top"><span className="status-dot"/><small>{t.delivery_mode==='ROOM'?'ROOM · SAME GENDER':'OPEN TASK'}</small></div><h3>{t.title}</h3><p>{t.pickup_location_text} → {t.destination_location_text}</p><div className="chips"><i>{naira(t.estimated_item_cost_kobo)} item capital</i><i>requester offered {naira(t.proposed_runner_fee_kobo)}</i><i>{t.proposed_eta_minutes} min</i></div></div><button className="btn dark" onClick={()=>{setSelected(t);setFee(String(Math.round(t.proposed_runner_fee_kobo/100)))}}>Offer</button></article>)}</div>{tasks.length===0&&<div className="card success"><h2>No open tasks right now.</h2><p className="sub">A good runner market starts with dense campus demand.</p><Link className="btn ghost" href="/do">Create a request →</Link></div>}
 {selected&&<div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div id="offer-dialog" className="sheet" role="dialog" aria-modal="true" aria-labelledby="offer-dialog-title"><div className="sheet-handle" aria-hidden="true"/><div className="eyebrow">YOUR OFFER</div><h2 id="offer-dialog-title">{selected.title}</h2><p className="sub">{selected.pickup_location_text} → {selected.destination_location_text}</p><div className="grid2"><label>Your fee<input inputMode="numeric" value={fee} onChange={e=>setFee(e.target.value)}/></label><label>Your ETA<input inputMode="numeric" value={eta} onChange={e=>setEta(e.target.value)}/></label></div><label>How much can you front?<input inputMode="numeric" value={float} onChange={e=>setFloat(e.target.value)} placeholder="5000"/></label><label>Message <span className="muted-inline">optional</span><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="I’m already near the pickup."/></label>{error&&<div className="error">{error}</div>}<button className="btn dark full" disabled={busy||Number(fee)<=0} onClick={offer}>{busy?'Sending…':'Send offer →'}</button><button className="btn ghost full" onClick={()=>setSelected(null)}>Cancel</button></div></div>}
 </main></AppShell>
}
