'use client';
import{useCallback,useEffect,useState}from'react';import{useParams,useRouter}from'next/navigation';import Link from'next/link';import{AppShell}from'@/src/components/AppShell';import{naira}from'@/src/lib/app-config';import{readLocationQueue,queueLocation,removeQueued}from'@/src/lib/offline-queue';
const flow=['FUNDED','IN_PROGRESS','AT_VENDOR','PRICE_ADJUSTMENT_PENDING','ITEM_CONFIRMED','EN_ROUTE','HANDOFF_PENDING','COMPLETED'];
const next:any={FUNDED:'IN_PROGRESS',IN_PROGRESS:'AT_VENDOR',AT_VENDOR:'ITEM_CONFIRMED',ITEM_CONFIRMED:'EN_ROUTE',EN_ROUTE:'HANDOFF_PENDING'};
export default function Order(){const{id}=useParams<{id:string}>();const router=useRouter();const[t,setT]=useState<any>(null),[viewer,setViewer]=useState(''),[bids,setBids]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[body,setBody]=useState(''),[error,setError]=useState(''),[trackOn,setTrackOn]=useState(false),[tracking,setTracking]=useState<any>(null),[adjustments,setAdjustments]=useState<any[]>([]),[newCost,setNewCost]=useState(''),[reason,setReason]=useState(''),[pin,setPin]=useState(''),[handoff,setHandoff]=useState<any>(null),[handoffPin,setHandoffPin]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [a,b,m,l,p,h]=await Promise.all([fetch('/api/tasks/'+id).then(r=>r.json()),fetch('/api/tasks/'+id+'/bids').then(r=>r.json()),fetch('/api/tasks/'+id+'/messages').then(r=>r.json()).catch(()=>({messages:[]})),fetch('/api/tasks/'+id+'/location').then(r=>r.json()).catch(()=>({session:null})),fetch('/api/tasks/'+id+'/price-adjustment').then(r=>r.json()).catch(()=>({adjustments:[]})),fetch('/api/tasks/'+id+'/handoff').then(r=>r.json()).catch(()=>({handoff:null}))]);setT(a.task);setViewer(a.viewer_id||m.viewer_id||'');setBids(b.bids||[]);setMessages(m.messages||[]);setTracking(l);setAdjustments(p.adjustments||[]);setHandoff(h.handoff)},[id]);
 useEffect(()=>{void load();const tm=setInterval(()=>{void load()},6000);return()=>clearInterval(tm)},[load]);
 useEffect(()=>{if(!trackOn||!navigator.geolocation)return;let seq=Number(localStorage.getItem('cg:seq:'+id)||0);const send=(p:GeolocationPosition)=>{seq+=1;localStorage.setItem('cg:seq:'+id,String(seq));const x={taskId:id,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,captured_at:new Date().toISOString(),sequence:seq};const post=()=>fetch('/api/tasks/'+id+'/location',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x)}).then(()=>removeQueued(id,seq)).catch(()=>queueLocation(x));if(navigator.onLine)post();else queueLocation(x)};const watch=navigator.geolocation.watchPosition(send,()=>setError('Location permission was not granted. Chat and handoff verification still work.'),{enableHighAccuracy:false,maximumAge:30000,timeout:15000});const retry=setInterval(()=>{if(!navigator.onLine)return;for(const x of readLocationQueue().filter(q=>q.taskId===id)){fetch('/api/tasks/'+id+'/location',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x)}).then(()=>removeQueued(id,x.sequence)).catch(()=>{})}},60000);return()=>{navigator.geolocation.clearWatch(watch);clearInterval(retry)}},[id,trackOn]);
 async function msg(){const x=body.trim();if(!x)return;const r=await fetch('/api/tasks/'+id+'/messages',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body:x})}),j=await r.json();if(!r.ok){setError(j.error||'Message failed.');return}setBody('');setMessages(v=>[...v,j.message])}
 async function advance(s:string){setBusy(true);const r=await fetch('/api/tasks/'+id+'/status',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({next_status:s})}),j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Could not update status.');return}load()}
 async function accept(bid:string){const r=await fetch('/api/tasks/'+id+'/accept',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bid_id:bid})}),j=await r.json();if(!r.ok){setError(j.error||'Could not accept offer.');return}router.push(j.redirect)}
 async function requestAdjustment(){const amount=Math.round(Number(newCost||0)*100);const r=await fetch('/api/tasks/'+id+'/price-adjustment',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({new_item_cost_kobo:amount,reason})}),j=await r.json();if(!r.ok){setError(j.error||'Could not request adjustment.');return}setNewCost('');setReason('');load()}
 async function decision(action:string,adjustmentId:string){const r=await fetch('/api/tasks/'+id+'/price-adjustment',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action,adjustment_id:adjustmentId})}),j=await r.json();if(!r.ok){setError(j.error||'Could not update adjustment.');return}load()}
 async function rotate(){const r=await fetch('/api/tasks/'+id+'/handoff',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'rotate'})}),j=await r.json();if(!r.ok){setError(j.error||'Could not create a handoff code.');return}setHandoffPin(j.pin)}
 async function verify(){setBusy(true);const r=await fetch('/api/tasks/'+id+'/handoff',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'verify',pin})}),j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Could not verify handoff.');return}setPin('');load()}
 async function retryVariance(adjustmentId:string){const r=await fetch('/api/tasks/'+id+'/price-adjustment/fund',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({adjustment_id:adjustmentId})}),j=await r.json();if(!r.ok){setError(j.error||'Could not fund variance.');return}load()}
 if(!t)return <AppShell><main className="shell app-page"><div className="card form"><h2>Loading task…</h2></div></main></AppShell>;
 const idx=flow.indexOf(t.status),latest=adjustments[0],payer=t.payer_id===viewer,runner=t.runner_id===viewer;
 return <AppShell><main className="shell app-page">
  <div className="page-top"><div><div className="eyebrow">TASK · {t.status.replaceAll('_',' ')}</div><h1 className="app-title">{t.title}</h1><p className="sub">{t.pickup_location_text} → {t.destination_location_text}{t.delivery_mode==='ROOM'?' · same-gender room':''}</p></div><Link className="btn ghost" href="/orders">Orders</Link></div>
  {error&&<div className="error">{error}</div>}
  <div className="track-grid card"><div className="tracking-map"><div className="road r1"/><div className="road r2"/><div className="node" style={{left:'28%',top:'60%'}}><span/>Pickup</div><div className="node" style={{left:'72%',top:'60%'}}><span/>Drop</div><div className="track-runner" style={{left:'50%',top:'53%'}}>R</div><div className="map-tag">{tracking?.session?'Active delivery telemetry':'Tracking starts when execution begins'}</div></div><div className="track-side"><small>DELIVERY STATUS</small><b>{t.status.replaceAll('_',' ')}</b><span>{tracking?.session?.last_runner_at?'Runner ping '+new Date(tracking.session.last_runner_at).toLocaleTimeString():'Waiting for runner'}</span><span>{tracking?.session?.last_payer_at?'Customer ping '+new Date(tracking.session.last_payer_at).toLocaleTimeString():'Customer location not yet shared'}</span><button className={'btn '+(trackOn?'lime':'ghost')} onClick={()=>setTrackOn(v=>!v)}>{trackOn?'Location sharing on':'Share my location'}</button><small>Location is session-scoped and can be queued during weak network.</small></div></div>
  <div className="timeline">{flow.map((s,i)=><div key={s} className={i<=idx?'on':''}><small>{i+1}</small><b>{s.replaceAll('_',' ')}</b></div>)}</div>
  {(t.status==='OPEN'||t.status==='NEGOTIATING')&&<section className="section-tight"><div className="section-label"><span>OFFERS</span><span>{bids.length} active</span></div><div className="task-list">{bids.map(b=><article className="card task" key={b.id}><div><b>{b.runner?.display_name||'Runner'}</b><span>{b.message||'No message'} · {b.eta_minutes} min · float {naira(b.runner_float_capacity_kobo)}</span></div><div className="task-action"><strong>{naira(b.fee_kobo)}</strong>{payer&&<button className="btn dark" onClick={()=>accept(b.id)}>Accept</button>}</div></article>)}</div></section>}
  {t.status==='AGREED'&&payer&&<div className="card form"><div className="section-label"><span>AGREEMENT READY</span><span>Escrow next</span></div><p className="sub">The runner, fee and ETA are fixed for this agreement. Fund it before the runner can start.</p><Link className="btn dark full" href={'/fund/'+id}>Fund task →</Link></div>}
  {t.status==='AT_VENDOR'&&runner&&<section className="section-tight"><div className="card form"><div className="section-label"><span>PRICE GUARD</span><span>Nothing moves silently</span></div><h2>Actual price changed?</h2><p className="sub">Ask the customer to approve the new item cost. CarryGo will not increase the escrow without an explicit approval and top-up.</p><label>New total item cost<input inputMode="numeric" value={newCost} onChange={e=>setNewCost(e.target.value)} placeholder="e.g. 3200"/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Vendor price was higher"/></label><button className="btn dark" disabled={!newCost||!reason} onClick={requestAdjustment}>Request approval →</button></div></section>}
  {t.status==='PRICE_ADJUSTMENT_PENDING'&&latest&&<section className="section-tight"><div className="card form"><div className="section-label"><span>PRICE CHANGE</span><span>{naira(latest.variance_kobo)} more</span></div><h2>Customer approval needed.</h2><p className="sub">Runner says the item now costs {naira(latest.new_item_cost_kobo)} instead of {naira(latest.previous_item_cost_kobo)}.</p><p className="soft-note">{latest.reason}</p>{payer&&<div className="actions"><button className="btn dark" onClick={()=>decision('approve',latest.id)}>Approve + fund →</button><button className="btn ghost" onClick={()=>decision('reject',latest.id)}>Decline</button></div>}</div></section>}
  {latest?.status==='APPROVED'&&payer&&<section className="section-tight"><div className="card form"><div className="section-label"><span>TOP-UP REQUIRED</span><span>{naira(latest.variance_kobo)}</span></div><p className="sub">The approval is recorded. Fund only the difference from your wallet.</p><button className="btn dark" onClick={()=>retryVariance(latest.id)}>Fund difference →</button></div></section>}
  {t.status==='HANDOFF_PENDING'&&<section className="section-tight"><div className="card form"><div className="section-label"><span>HANDOFF</span><span>PIN verified on completion</span></div>{payer&&<>{handoffPin?<div className="pin-display"><small>YOUR CURRENT CODE</small><strong>{handoffPin}</strong></div>:<button className="btn dark" onClick={rotate}>Show a new handoff code</button>}<div className="soft-note">Give the code to the runner only when the delivery is in your hands.</div></>}{runner&&<><label>Enter customer handoff code<input className="pin-box" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6 digits"/></label><button className="btn lime" disabled={busy||pin.length!==6} onClick={verify}>Verify and complete →</button></>}</div></section>}
  {['OPEN','NEGOTIATING','AGREED','FUNDING','FUNDED'].includes(t.status)&&<button className="btn ghost" disabled={busy} onClick={async()=>{if(!window.confirm('Cancel this task?'))return;setBusy(true);const r=await fetch('/api/tasks/'+id+'/cancel',{method:'POST'});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Could not cancel.');return}load()}}>Cancel task</button>}<section className="section-tight"><div className="section-label"><span>CHAT</span><span>Location questions belong here</span></div><div className="card chat"><div className="chat-list">{messages.map(m=><div key={m.id} className={m.sender_id===viewer?'bubble me':'bubble'}>{m.body}<small>{new Date(m.created_at).toLocaleTimeString()}</small></div>)}</div><div className="chat-compose"><input value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')msg()}} placeholder="Confirm the exact pickup point…"/><button className="btn dark" onClick={msg}>Send</button></div></div></section>
 </main></AppShell>
}
