'use client';
import{useCallback,useEffect,useRef,useState}from'react';import{useParams,useRouter}from'next/navigation';import Link from'next/link';import{AppShell}from'@/src/components/AppShell';import{naira}from'@/src/lib/app-config';import{readLocationQueue,queueLocation,removeQueued}from'@/src/lib/offline-queue';
const flow=['FUNDED','IN_PROGRESS','AT_VENDOR','PRICE_ADJUSTMENT_PENDING','ITEM_CONFIRMED','EN_ROUTE','HANDOFF_PENDING','COMPLETED'];
const terminal=new Set(['COMPLETED','CANCELLED','EXPIRED','FAILED','DISPUTED','ABANDONED']);
function pct(value:any){const n=Number(value||0);return n<=1?Math.round(n*100):Math.round(n)}
function verificationScore(value:string){return value==='UNIVERSITY_VERIFIED'?4:value==='CAMPUS_VERIFIED'?3:value==='PHONE_VERIFIED'?2:1}
function offerScore(b:any){const r=b.reputation||{};return pct(r.reliability_score)*0.38+pct(r.on_time_rate)*0.24+pct(r.completion_rate)*0.18+verificationScore(b.runner?.verification_level||'UNVERIFIED')*5+Math.max(0,100-Math.min(100,Number(b.fee_kobo||0)/10))*0.05+Math.max(0,100-Math.min(100,Number(b.eta_minutes||60)))*0.1}
function actionFor(status:string,payer:boolean,runner:boolean){if(payer){if(status==='OPEN'||status==='NEGOTIATING')return['Choose a runner','Compare the offers below before you commit.'];if(status==='AGREED')return['Fund the task','The runner is selected. Nothing starts until you fund it.'];if(status==='FUNDED')return['Your runner is getting ready','You can watch the task here as execution begins.'];if(status==='IN_PROGRESS')return['Runner is on the way to pickup','No action yet. Keep the chat nearby if pickup details change.'];if(status==='AT_VENDOR')return['Runner is checking the item','You will be asked only if the item price changes.'];if(status==='PRICE_ADJUSTMENT_PENDING')return['Review the price change','Approve or decline the difference before anything is charged.'];if(status==='ITEM_CONFIRMED')return['Your item is secured','The runner is moving it to the destination.'];if(status==='EN_ROUTE')return['Delivery is moving','Share the live status when someone else needs the update.'];if(status==='HANDOFF_PENDING')return['Be ready for handoff','Only reveal the handoff code when the runner is physically there.'];if(status==='COMPLETED')return['Task complete','Need the same thing again? Repeat the useful parts in one tap.']}if(runner){if(status==='AGREED')return['Wait for funding','The task details are fixed. Start only after funding lands.'];if(status==='FUNDED')return['Start the task','Once you are ready, mark the task in progress.'];if(status==='IN_PROGRESS')return['Go to pickup','Mark At pickup once you are with the vendor or pickup point.'];if(status==='AT_VENDOR')return['Confirm the item','Once the requested item is secured, continue the task.'];if(status==='ITEM_CONFIRMED')return['Head to destination','Mark En route when you leave pickup.'];if(status==='EN_ROUTE')return['Complete the handoff','Mark Handoff pending when you are at the destination.'];if(status==='HANDOFF_PENDING')return['Verify handoff','Enter the customer code to complete the task.'];if(status==='COMPLETED')return['Task complete','This route is now part of your reliability history.']};return['Task status','CarryGo will surface the next useful action here.']}
export default function Order(){const{id}=useParams<{id:string}>();const router=useRouter();const[t,setT]=useState<any>(null),[viewer,setViewer]=useState(''),[bids,setBids]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[body,setBody]=useState(''),[error,setError]=useState(''),[trackOn,setTrackOn]=useState(false),[tracking,setTracking]=useState<any>(null),[adjustments,setAdjustments]=useState<any[]>([]),[newCost,setNewCost]=useState(''),[reason,setReason]=useState(''),[receipt,setReceipt]=useState<File|null>(null),[pin,setPin]=useState(''),[handoff,setHandoff]=useState<any>(null),[handoffPin,setHandoffPin]=useState(''),[busy,setBusy]=useState(false),[shareBusy,setShareBusy]=useState(false),[shareUrl,setShareUrl]=useState(''),[sort,setSort]=useState<'fit'|'fee'|'eta'>('fit'),[replyTo,setReplyTo]=useState<any|null>(null),[peerTyping,setPeerTyping]=useState(false);
 const load=useCallback(async()=>{const r=await fetch('/api/tasks/'+id,{cache:'no-store'});const a=await r.json();if(!r.ok){setError(a.error||'Could not load this task.');return}setT(a.task);setViewer(a.viewer_id||'');setBids(a.bids||[]);setItems(a.items||[]);setMessages(a.messages||[]);setTracking(a.tracking||{session:null});setAdjustments(a.adjustments||[]);setHandoff(a.handoff||null)},[id]);
 useEffect(()=>{const first=window.setTimeout(()=>{void load()},0);const tm=setInterval(()=>{void load()},8000);return()=>{clearTimeout(first);clearInterval(tm)}},[load]);
 useEffect(()=>{const tm=setInterval(()=>{fetch('/api/tasks/'+id+'/presence',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(j=>{if(j)setPeerTyping(Boolean(j.typing))}).catch(()=>{})},1800);return()=>clearInterval(tm)},[id]);
 useEffect(()=>{const active=body.trim().length>0;fetch('/api/tasks/'+id+'/presence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({is_typing:active})}).catch(()=>{});const tm=active?window.setTimeout(()=>fetch('/api/tasks/'+id+'/presence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({is_typing:false})}).catch(()=>{}),900):undefined;return()=>{if(tm)clearTimeout(tm)}},[body,id]);
 useEffect(()=>{if(!trackOn||!navigator.geolocation)return;let seq=Number(localStorage.getItem('cg:seq:'+id)||0);const send=(p:GeolocationPosition)=>{seq+=1;localStorage.setItem('cg:seq:'+id,String(seq));const x={taskId:id,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,captured_at:new Date().toISOString(),sequence:seq};const post=()=>fetch('/api/tasks/'+id+'/location',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x)}).then(()=>removeQueued(id,seq)).catch(()=>queueLocation(x));if(navigator.onLine)post();else queueLocation(x)};const watch=navigator.geolocation.watchPosition(send,()=>setError('Location permission was not granted. Chat and handoff verification still work.'),{enableHighAccuracy:false,maximumAge:30000,timeout:15000});const retry=setInterval(()=>{if(!navigator.onLine)return;for(const x of readLocationQueue().filter(q=>q.taskId===id)){fetch('/api/tasks/'+id+'/location',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x)}).then(()=>removeQueued(id,x.sequence)).catch(()=>{})}},60000);return()=>{navigator.geolocation.clearWatch(watch);clearInterval(retry)}},[id,trackOn]);
 async function msg(){const x=body.trim();if(!x)return;const r=await fetch('/api/tasks/'+id+'/messages',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body:x,reply_to_message_id:replyTo?.id||null})}),j=await r.json();if(!r.ok){setError(j.error||'Message failed.');return}setBody('');setReplyTo(null);setMessages(v=>[...v,j.message]);fetch('/api/tasks/'+id+'/presence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({is_typing:false})}).catch(()=>{})}
 async function advance(s:string){setBusy(true);const r=await fetch('/api/tasks/'+id+'/status',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({next_status:s})}),j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Could not update status.');return}load()}
 async function accept(bid:string){const r=await fetch('/api/tasks/'+id+'/accept',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bid_id:bid})}),j=await r.json();if(!r.ok){setError(j.error||'Could not accept offer.');return}router.push(j.redirect)}
 async function requestAdjustment(){const amount=Math.round(Number(newCost||0)*100);const form=new FormData();form.set('new_item_cost_kobo',String(amount));form.set('reason',reason);if(receipt)form.set('receipt',receipt);const r=await fetch('/api/tasks/'+id+'/price-adjustment',{method:'POST',body:form}),j=await r.json();if(!r.ok){setError(j.error||'Could not request adjustment.');return}setNewCost('');setReason('');setReceipt(null);load()}
 async function decision(action:string,adjustmentId:string){const r=await fetch('/api/tasks/'+id+'/price-adjustment',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action,adjustment_id:adjustmentId})}),j=await r.json();if(!r.ok){setError(j.error||'Could not update adjustment.');return}load()}
 async function rotate(){const r=await fetch('/api/tasks/'+id+'/handoff',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'rotate'})}),j=await r.json();if(!r.ok){setError(j.error||'Could not create a handoff code.');return}setHandoffPin(j.pin)}
 async function verify(){setBusy(true);const r=await fetch('/api/tasks/'+id+'/handoff',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'verify',pin})}),j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Could not verify handoff.');return}setPin('');load()}
 async function retryVariance(adjustmentId:string){const r=await fetch('/api/tasks/'+id+'/price-adjustment/fund',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({adjustment_id:adjustmentId})}),j=await r.json();if(!r.ok){setError(j.error||'Could not fund variance.');return}load()}
 async function repeat(){setBusy(true);const r=await fetch('/api/tasks/'+id+'/repeat',{method:'POST'}),j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Could not repeat this task.');return}router.push('/orders/'+j.task.id)}
 async function shareStatus(){setShareBusy(true);const r=await fetch('/api/tasks/'+id+'/share',{method:'POST'}),j=await r.json();setShareBusy(false);if(!r.ok){setError(j.error||'Could not create a status link.');return}const url=window.location.origin+j.url;setShareUrl(url);try{await navigator.clipboard.writeText(url)}catch{}}
 if(!t)return <AppShell><main className="shell app-page"><div className="card form"><h2>Loading task…</h2></div></main></AppShell>;
 const idx=flow.indexOf(t.status),latest=adjustments[0],payer=t.payer_id===viewer,runner=t.runner_id===viewer;
 const action=actionFor(t.status,payer,runner);
 const sortedBids=[...bids].sort((a,b)=>sort==='fee'?Number(a.fee_kobo)-Number(b.fee_kobo):sort==='eta'?Number(a.eta_minutes)-Number(b.eta_minutes):offerScore(b)-offerScore(a));
 const nextRunnerStatus=t.status==='FUNDED'?'IN_PROGRESS':t.status==='IN_PROGRESS'?'AT_VENDOR':t.status==='AT_VENDOR'?'ITEM_CONFIRMED':t.status==='ITEM_CONFIRMED'?'EN_ROUTE':t.status==='EN_ROUTE'?'HANDOFF_PENDING':null;
 return <AppShell><main className="shell app-page">
  <div className="page-top"><div><div className="eyebrow">TASK · {t.status.replaceAll('_',' ')}</div><h1 className="app-title">{t.title}</h1><p className="sub">{t.pickup_location_text} → {t.destination_location_text}{t.delivery_mode==='ROOM'?' · same-gender room':''}</p></div><Link className="btn ghost" href="/orders">Orders</Link></div>
  {error&&<div className="error" role="alert">{error}</div>}
  <section className="card next-action"><div><small>DO THIS NOW</small><h2>{action[0]}</h2><p className="sub">{action[1]}</p></div>{payer&&t.status==='AGREED'&&<Link className="btn dark" href={'/fund/'+id}>Fund task →</Link>}{runner&&nextRunnerStatus&&<button type="button" className="btn dark" disabled={busy} onClick={()=>advance(nextRunnerStatus)}>{busy?'Updating…':nextRunnerStatus==='HANDOFF_PENDING'?'At destination →':nextRunnerStatus==='ITEM_CONFIRMED'?'Item secured →':nextRunnerStatus==='EN_ROUTE'?'Start delivery →':nextRunnerStatus==='AT_VENDOR'?'At pickup →':'Start task →'}</button>}{payer&&t.status==='COMPLETED'&&<button type="button" className="btn dark" disabled={busy} onClick={repeat}>{busy?'Creating…':'Do this again →'}</button>}</section>
  {items.length>0&&<div className="task-detail-strip"><span>ITEM</span><b>{items.map(x=>String(x.quantity)+' × '+x.name).join(' · ')}</b></div>}
  <div className="track-grid card"><div className="tracking-map" aria-hidden="true"><div className="road r1"/><div className="road r2"/><div className="node" style={{left:'28%',top:'60%'}}><span/>Pickup</div><div className="node" style={{left:'72%',top:'60%'}}><span/>Drop</div><div className="track-runner" style={{left:'50%',top:'53%'}}>R</div><div className="map-tag">{tracking?.session?'Active delivery telemetry':'Tracking starts when execution begins'}</div></div><div className="track-side"><small>DELIVERY STATUS</small><b>{t.status.replaceAll('_',' ')}</b><span>{tracking?.session?.last_runner_at?'Runner ping '+new Date(tracking.session.last_runner_at).toLocaleTimeString():'Waiting for runner'}</span><button type="button" className={'btn '+(trackOn?'lime':'ghost')} onClick={()=>setTrackOn(v=>!v)} aria-pressed={trackOn}>{trackOn?'Location sharing on':'Share my location'}</button>{!terminal.has(t.status)&&<button type="button" className="btn ghost" disabled={shareBusy} onClick={shareStatus}>{shareBusy?'Creating link…':'Share live status'}</button>}{shareUrl&&<small className="share-confirm">Link copied. Expires in 2 hours.</small>}<small>Shared status shows only this delivery, not your account or location history.</small></div></div>
  <details className="workflow-details"><summary>See full delivery flow</summary><div className="timeline" aria-label="Task progress">{flow.map((s,i)=><div key={s} className={i<=idx?'on':''} aria-current={s===t.status?'step':undefined}><small>{i+1}</small><b>{s.replaceAll('_',' ')}</b></div>)}</div></details>
  {(t.status==='OPEN'||t.status==='NEGOTIATING')&&<section className="section-tight"><div className="section-label"><span>OFFERS</span><span>{bids.length} active</span></div><div className="offer-sort"><button className={sort==='fit'?'filter active':'filter'} onClick={()=>setSort('fit')}>Best fit</button><button className={sort==='fee'?'filter active':'filter'} onClick={()=>setSort('fee')}>Lowest fee</button><button className={sort==='eta'?'filter active':'filter'} onClick={()=>setSort('eta')}>Fastest</button></div><div className="task-list">{sortedBids.map(b=><article className="card task offer-card" key={b.id}><div><b>{b.runner?.display_name||'Runner'}</b><div className="offer-trust"><span>{b.runner?.verification_level?.replaceAll('_',' ')||'Not verified'}</span><span>{b.reputation?.total_completed||0} completed</span><span>{pct(b.reputation?.on_time_rate||0)}% on time</span><span>{b.reputation?.trust_band||'Building history'}</span></div><span>{b.message||'No message'} · {b.eta_minutes} min · float {naira(b.runner_float_capacity_kobo)}</span></div><div className="task-action"><strong>{naira(b.fee_kobo)}</strong>{payer&&<button type="button" className="btn dark" onClick={()=>accept(b.id)}>Choose</button>}</div></article>)}</div></section>}
  {t.status==='AGREED'&&payer&&<div className="card form"><div className="section-label"><span>AGREEMENT READY</span><span>Escrow next</span></div><p className="sub">The runner, fee and ETA are fixed for this agreement. Fund it before the runner can start.</p><Link className="btn dark full" href={'/fund/'+id}>Fund task →</Link></div>}
  {t.status==='AT_VENDOR'&&runner&&<section className="section-tight"><div className="card form"><div className="section-label"><span>PRICE GUARD</span><span>Nothing moves silently</span></div><h2>Actual price changed?</h2><p className="sub">Ask the customer to approve the new item cost. CarryGo will not increase the escrow without an explicit approval and top-up.</p><label>New total item cost<input inputMode="numeric" value={newCost} onChange={e=>setNewCost(e.target.value)} placeholder="e.g. 3200"/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Vendor price was higher"/></label><label>Receipt <span className="muted-inline">optional · JPEG, PNG or WebP · 3 MB max</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setReceipt(e.target.files?.[0]||null)}/></label>{receipt&&<small className="hint">Attached: {receipt.name}</small>}<button type="button" className="btn dark" disabled={!newCost||!reason} onClick={requestAdjustment}>Request approval →</button></div></section>}
  {t.status==='PRICE_ADJUSTMENT_PENDING'&&latest&&<section className="section-tight"><div className="card form"><div className="section-label"><span>PRICE CHANGE</span><span>{naira(latest.variance_kobo)} more</span></div><h2>Customer approval needed.</h2><p className="sub">Runner says the item now costs {naira(latest.new_item_cost_kobo)} instead of {naira(latest.previous_item_cost_kobo)}.</p><p className="soft-note">{latest.reason}</p>{latest.evidence_url&&<a className="text-link" href={latest.evidence_url} target="_blank" rel="noreferrer">View receipt →</a>}{payer&&<div className="actions"><button type="button" className="btn dark" onClick={()=>decision('approve',latest.id)}>Approve + fund →</button><button type="button" className="btn ghost" onClick={()=>decision('reject',latest.id)}>Decline</button></div>}</div></section>}
  {latest?.status==='APPROVED'&&payer&&<section className="section-tight"><div className="card form"><div className="section-label"><span>TOP-UP REQUIRED</span><span>{naira(latest.variance_kobo)}</span></div><p className="sub">The approval is recorded. Fund only the difference from your wallet.</p><button type="button" className="btn dark" onClick={()=>retryVariance(latest.id)}>Fund difference →</button></div></section>}
  {t.status==='HANDOFF_PENDING'&&<section className="section-tight"><div className="card form"><div className="section-label"><span>HANDOFF</span><span>PIN verified on completion</span></div>{payer&&<>{handoffPin?<div className="pin-display"><small>YOUR CURRENT CODE</small><strong>{handoffPin}</strong></div>:<button type="button" className="btn dark" onClick={rotate}>Show a new handoff code</button>}<div className="soft-note">Give the code to the runner only when the delivery is in your hands.</div></>}{runner&&<><label>Enter customer handoff code<input className="pin-box" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6 digits"/></label><button type="button" className="btn lime" disabled={busy||pin.length!==6} onClick={verify}>Verify and complete →</button></>}</div></section>}
  {['OPEN','NEGOTIATING','AGREED','FUNDING','FUNDED'].includes(t.status)&&<button type="button" className="btn ghost" disabled={busy} onClick={async()=>{if(!window.confirm('Cancel this task?'))return;setBusy(true);const r=await fetch('/api/tasks/'+id+'/cancel',{method:'POST'});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Could not cancel.');return}load()}}>Cancel task</button>}
  <section className="section-tight"><div className="section-label"><span>CHAT</span><span>Location questions belong here</span></div><div className="card chat"><div className="chat-list" aria-live="polite">{messages.map(m=><div key={m.id} className={m.sender_id===viewer?'bubble me':'bubble'} onPointerDown={e=>{(e.currentTarget as HTMLElement).dataset.swipeX=String(e.clientX)}} onPointerUp={e=>{const start=Number((e.currentTarget as HTMLElement).dataset.swipeX||e.clientX);if(e.clientX-start>55)setReplyTo(m)}}><button type="button" className="message-reply-trigger" aria-label={"Reply to "+(m.sender_id===viewer?'your':'their')+" message"} onClick={()=>setReplyTo(m)}>↩</button>{m.reply_to&&<div className="reply-quote"><b>{m.reply_to.sender_id===viewer?'You':'Reply'}</b><span>{m.reply_to.body}</span></div>}<span>{m.body}</span><small>{new Date(m.created_at).toLocaleTimeString()}</small></div>)}</div>{peerTyping&&<div className="typing-cue" role="status"><i/><i/><i/><span>They’re replying…</span></div>{'}'}{replyTo&&<div className="reply-preview"><div><small>REPLYING TO</small><b>{replyTo.sender_id===viewer?'You':replyTo.body?.slice(0,80)}</b></div><button type="button" onClick={()=>setReplyTo(null)} aria-label="Cancel reply">×</button></div>}<div className="chat-compose"><input aria-label="Message" value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void msg()}}} placeholder="Confirm the exact pickup point…"/><button type="button" className="btn dark" onClick={()=>void msg()}>Send</button></div></div></section>
 </main></AppShell>
}
