'use client';

import{useEffect,useState}from'react';
import{AppShell}from'@/src/components/AppShell';
import{naira}from'@/src/lib/app-config';

export default function Wallet(){
 const[d,setD]=useState<any>(null),[amount,setAmount]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[accountForm,setAccountForm]=useState(false),[banks,setBanks]=useState<any[]>([]),[bankLoading,setBankLoading]=useState(false),[bankCode,setBankCode]=useState(''),[accountNumber,setAccountNumber]=useState(''),[accountName,setAccountName]=useState('');
 useEffect(()=>{fetch('/api/wallet/withdraw').then(r=>r.json()).then(setD).catch(()=>setD({error:'Could not load wallet.'}))},[]);
 async function topup(){setBusy(true);setMsg('');const r=await fetch('/api/wallet/topup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount_kobo:Math.round(Number(amount||0)*100)})}),j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error||'Could not start top-up.');return}window.location.assign(j.authorization_url)}
 async function loadBanks(){if(banks.length||bankLoading)return;setBankLoading(true);const r=await fetch('/api/wallet/banks');const j=await r.json();setBankLoading(false);if(r.ok)setBanks(j.banks||[]);else setMsg(j.error||'Could not load banks.')}
 async function saveAccount(){setBusy(true);setMsg('');const r=await fetch('/api/wallet/payout-account',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bank_code:bankCode,account_number:accountNumber,account_name:accountName})}),j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error||'Could not save payout account.');return}setD((x:any)=>({...x,account:j.account}));setAccountForm(false);setBankCode('');setAccountNumber('');setAccountName('');}
 async function withdraw(){setBusy(true);setMsg('');const r=await fetch('/api/wallet/withdraw',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({payout_account_id:d.account.id,amount_kobo:Math.round(Number(amount||0)*100)})}),j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error||'Could not start withdrawal.');return}setMsg(j.status==='SUCCESS'?'Payout sent.':'Payout is processing.');setAmount('');const fresh=await fetch('/api/wallet/withdraw').then(r=>r.json());setD(fresh)}
 if(!d)return <AppShell><main className="shell app-page"><div className="card form"><h2>Loading wallet…</h2></div></main></AppShell>;
 if(d.error)return <AppShell><main className="shell app-page narrow"><div className="card form"><h2>{d.error}</h2></div></main></AppShell>;
 const w=d.wallet||{},payable=Number(w.runner_payable_kobo||0);
 return <AppShell><main className="shell app-page narrow">
  <div className="page-top"><div><div className="eyebrow">WALLET</div><h1 className="app-title">Ready before you <em>need it.</em></h1><p className="sub">Top up once. Fund tasks in a tap. Your runner earnings are kept separate and can be paid out to your bank.</p></div></div>
  <div className="wallet-stats"><div className="dark-card"><small>AVAILABLE</small><div className="streak-big">{naira(w.available_kobo||0)}</div><p>Money you can use for a new task.</p></div><div className="card wallet-earnings"><small>RUNNER EARNINGS</small><strong>{naira(payable)}</strong><span>Available to withdraw.</span></div></div>
  <div className="card form"><h2>Add money</h2><div className="amount-presets">{['1000','2500','5000','10000'].map(v=><button type="button" key={v} className="mini-choice" onClick={()=>setAmount(v)}>₦{Number(v).toLocaleString()}</button>)}</div><label>Amount<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,''))} placeholder="e.g. 2500"/></label>{msg&&<div className="error" role="alert">{msg}</div>}<button className="btn dark full" disabled={busy||Number(amount)<100} onClick={topup}>{busy?'Opening Paystack…':'Add to wallet →'}</button><small className="hint">Payment is verified server-side before wallet value is created.</small></div>
  <div className="card form"><div className="section-label"><span>PAYOUT ACCOUNT</span><span>{d.account?'READY':'NOT SET'}</span></div>{d.account&&!accountForm?<><div className="payout-account"><div><b>{d.account.bank_name||'Bank account'}</b><span>{d.account.account_name} · ending {d.account.account_number_last4}</span></div><button type="button" className="btn ghost" onClick={()=>{setAccountForm(true);void loadBanks()}}>Change</button></div><label>Withdraw amount<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,''))} placeholder="Minimum ₦2,000"/></label><button className="btn dark full" disabled={busy||payable<200000||Number(amount)*100>payable||Number(amount)<2000} onClick={withdraw}>{busy?'Sending…':'Withdraw to bank →'}</button></>:<><p className="sub">Your bank details go to Paystack to create a transfer recipient. CarryGo stores only the recipient code and last four digits.</p><label>Bank<select value={bankCode} onChange={e=>setBankCode(e.target.value)} onFocus={loadBanks}><option value="">{bankLoading?'Loading banks…':'Choose your bank'}</option>{banks.map(b=><option key={b.code} value={b.code}>{b.name}</option>)}</select></label><label>Account number<input inputMode="numeric" maxLength={10} value={accountNumber} onChange={e=>setAccountNumber(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10 digits"/></label><label>Account name<input value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="Name on the bank account"/></label><div className="actions"><button className="btn dark" disabled={busy||bankCode.length<3||accountNumber.length!==10||accountName.trim().length<2} onClick={saveAccount}>{busy?'Verifying…':'Verify and save'}</button><button className="btn ghost" onClick={()=>setAccountForm(false)}>Cancel</button></div></>}</div>
  <section className="section-tight"><div className="section-label"><span>RECENT PAYOUTS</span><span>{d.withdrawals?.length||0}</span></div><div className="task-list">{(d.withdrawals||[]).map((x:any)=><article className="card task" key={x.id}><div><b>{naira(x.amount_kobo)}</b><span>{new Date(x.requested_at).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</span></div><strong>{x.status}</strong></article>)}</div></section>
 </main></AppShell>
}