"use client";
import { useMemo } from "react";
import { motion, useReducedMotion } from "motion/react";
export type PasswordRule={id:string;label:string;test:(value:string)=>boolean};
export const defaultPasswordRules:readonly PasswordRule[]=[
 {id:"length",label:"12 characters or more",test:v=>v.length>=12},
 {id:"case",label:"Upper and lower case",test:v=>/[a-z]/.test(v)&&/[A-Z]/.test(v)},
 {id:"digit",label:"A number",test:v=>/\d/.test(v)},
 {id:"symbol",label:"A symbol",test:v=>/[^a-zA-Z0-9]/.test(v)}
];
export function usePasswordStrength(value:string,rules=defaultPasswordRules){return useMemo(()=>{const evaluated=rules.map(r=>({...r,met:r.test(value)}));const passed=evaluated.filter(r=>r.met).length;const guessable=value.length>0&&( /^(?:password|passw0rd|qwerty|letmein|welcome|admin|123456)/i.test(value) || /(.)\\1{3,}/.test(value) );const score=value.length===0?0:guessable?1:Math.min(rules.length,Math.max(1,passed));const labels=["Empty","Weak","Fair","Good","Strong"];return{score,max:rules.length,label:labels[Math.min(score,4)],rules:evaluated,guessable}},[value,rules])}
export function PasswordStrength({value,rules=defaultPasswordRules}:{value:string;rules?:readonly PasswordRule[]}){const s=usePasswordStrength(value,rules);const reduce=useReducedMotion();const ratio=s.max?s.score/s.max:0;const bar=s.score===0?"bg-[var(--line)]":ratio<=.34?"bg-red-500":ratio<=.67?"bg-amber-500":"bg-emerald-500";const text=s.score===0?"text-[var(--muted)]":ratio<=.34?"text-red-600":ratio<=.67?"text-amber-600":"text-emerald-600";return <div className="w-full"><div role="meter" aria-label="Password strength" aria-valuemin={0} aria-valuemax={s.max} aria-valuenow={s.score} className="flex gap-1.5">{Array.from({length:s.max},(_,i)=><div key={i} className="relative h-1.5 flex-1 overflow-hidden rounded-full bg-[var(--paper)]"><motion.span className={"absolute inset-0 origin-left "+bar} initial={false} animate={{scaleX:i<s.score?1:0}} transition={reduce?{duration:0}:{type:"spring",stiffness:520,damping:34,mass:.45}}/></div>)}</div><div className="mt-2 flex justify-between text-[10px] font-semibold"><span className={text}>{s.label}</span>{s.guessable?<span className="text-amber-600">Commonly guessed</span>:null}</div><ul className="mt-3 grid gap-1.5">{s.rules.map(r=><li key={r.id} className="flex items-center gap-2 text-[10px]"><span className={"grid size-3.5 place-items-center rounded border "+(r.met?"border-emerald-500 bg-emerald-500 text-white":"border-[var(--line)]")}>{r.met?"✓":""}</span><span className={r.met?"":"text-[var(--muted)]"}>{r.label}</span></li>)}</ul></div>}
export default PasswordStrength;