'use client';
import{useEffect,useMemo,useRef,useState}from'react';
export type PlaceSuggestion={label:string;kind:string;locationId?:string};
async function loadPlaces(){const r=await fetch('/api/locations',{cache:'no-store'});if(!r.ok)return[];const j=await r.json();return(j.locations||[]).map((x:{id:string;name:string;location_type?:string})=>({label:x.name,locationId:x.id,kind:x.location_type==='HOSTEL'||x.location_type==='ROOM'?'Hostel':x.location_type==='FOOD'||x.location_type==='MERCHANT'||x.location_type==='SHOP'?'Food':x.location_type==='CAMPUS'?'Campus':'Landmark'}))}
export function LocationField({label,value,onChange,onSelect,placeholder}:{label:string;value:string;onChange:(v:string)=>void;onSelect?:(p:PlaceSuggestion)=>void;placeholder?:string}){
 const[open,setOpen]=useState(false),[places,setPlaces]=useState<PlaceSuggestion[]>([]),ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{let live=true;loadPlaces().then(v=>{if(live)setPlaces(v)}).catch(()=>{});return()=>{live=false}},[]);
 useEffect(()=>{const f=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',f);return()=>document.removeEventListener('mousedown',f)},[]);
 const items=useMemo(()=>{const q=value.trim().toLowerCase();if(!q)return places.slice(0,8);return places.filter(p=>p.label.toLowerCase().includes(q)).slice(0,8)},[places,value]);
 return <div className="field-wrap" ref={ref}><label>{label}<input value={value} onFocus={()=>setOpen(true)} onChange={e=>{onChange(e.target.value);setOpen(true)}} placeholder={placeholder} autoComplete="off" aria-autocomplete="list" aria-expanded={open&&items.length>0}/></label>{open&&items.length>0&&<div className="suggestions" role="listbox" aria-label={label+' suggestions'}>{items.map(p=><button type="button" className="suggestion" key={p.locationId||p.label} role="option" aria-selected={value===p.label} onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(p.label);onSelect?.(p);setOpen(false)}}><span className="suggestion-mark"/><span><b>{p.label}</b><small>{p.kind}</small></span></button>)}</div>}</div>
}