import{NextResponse}from'next/server';import crypto from'node:crypto';import{createSupabaseAdminClient}from'@/src/lib/supabase/admin';import{createSupabaseServerClient}from'@/src/lib/supabase/server';
async function ctx(id:string){const s=await createSupabaseServerClient();const{data:{user}}=await s.auth.getUser();if(!user)return{error:NextResponse.json({error:'Sign in required'},{status:401}),s,user:null};const{data:e}=await s.from('errands').select('id,payer_id,runner_id,status').eq('id',id).single();if(!e)return{error:NextResponse.json({error:'Task not found.'},{status:404}),s,user};if(e.payer_id!==user.id&&e.runner_id!==user.id)return{error:NextResponse.json({error:'Not a participant.'},{status:403}),s,user,e};return{s,user,e}};
const MAX_RECEIPT_BYTES=3*1024*1024;
function validReceipt(file:File){if(file.size<16||file.size>MAX_RECEIPT_BYTES)return false;return ['image/jpeg','image/png','image/webp'].includes(file.type)}
async function validMagic(file:File){const b=new Uint8Array(await file.slice(0,16).arrayBuffer());if(file.type==='image/jpeg')return b[0]===0xff&&b[1]===0xd8&&b[2]===0xff;if(file.type==='image/png')return b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47&&b[4]===0x0d&&b[5]===0x0a&&b[6]===0x1a&&b[7]===0x0a;if(file.type==='image/webp')return b[0]===0x52&&b[1]===0x49&&b[2]===0x46&&b[3]===0x46&&b[8]===0x57&&b[9]===0x45&&b[10]===0x42&&b[11]===0x50;return false}
export async function GET(_r:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params;const c=await ctx(id);if(c.error)return c.error;const{data,error}=await c.s.from('price_adjustments').select('id,errand_id,requested_by,previous_item_cost_kobo,new_item_cost_kobo,variance_kobo,reason,evidence_object_path,status,approved_by,approved_at,created_at').eq('errand_id',id).order('created_at',{ascending:false}).limit(5);if(error)return NextResponse.json({error:error.message},{status:400});const admin=createSupabaseAdminClient();const adjustments=await Promise.all((data||[]).map(async row=>{if(!row.evidence_object_path)return row;const signed=await admin.storage.from('task-evidence').createSignedUrl(row.evidence_object_path,300);return{...row,evidence_url:signed.data?.signedUrl||null}}));return NextResponse.json({adjustments})}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params;const c=await ctx(id);if(c.error)return c.error;if(c.user!.id!==c.e.runner_id)return NextResponse.json({error:'Only the assigned runner can request a price adjustment.'},{status:403});const{data:allowed,error:rateError}=await c.s.rpc('consume_rate_limit',{p_scope:'price-adjustment',p_limit:8,p_window_seconds:3600});if(rateError)return NextResponse.json({error:'Could not verify request limits. Try again.'},{status:503});if(!allowed)return NextResponse.json({error:'Too many price adjustment requests. Try again later.'},{status:429,headers:{'retry-after':'600'}});
let amount=0,reason='',file:File|null=null;const contentType=request.headers.get('content-type')||'';if(contentType.startsWith('multipart/form-data')){const form=await request.formData();amount=Math.max(1,Math.round(Number(String(form.get('new_item_cost_kobo')||0))));reason=String(form.get('reason')||'').trim().slice(0,500);const candidate=form.get('receipt');if(candidate instanceof File&&candidate.size)file=candidate}else{const b=await request.json().catch(()=>({}));amount=Math.max(1,Math.round(Number(b.new_item_cost_kobo||0)));reason=String(b.reason||'').trim().slice(0,500)}
if(!Number.isFinite(amount)||!reason)return NextResponse.json({error:'Enter the new item price and a reason.'},{status:400});
let path:string|null=null;const admin=createSupabaseAdminClient();if(file){if(!validReceipt(file)||!(await validMagic(file)))return NextResponse.json({error:'Receipt must be a JPEG, PNG or WebP image up to 3 MB.'},{status:400});const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp';path=`tasks/${id}/receipts/${crypto.randomUUID()}.${ext}`;const bytes=Buffer.from(await file.arrayBuffer());const{error:uploadError}=await admin.storage.from('task-evidence').upload(path,bytes,{contentType:file.type,upsert:false});if(uploadError)return NextResponse.json({error:'Could not upload receipt.'},{status:502})}
const{data,error}=await c.s.rpc('request_price_adjustment',{p_errand_id:id,p_new_item_cost_kobo:amount,p_reason:reason,p_evidence_object_path:path});if(error){if(path)await admin.storage.from('task-evidence').remove([path]);return NextResponse.json({error:error.message},{status:400})}return NextResponse.json({price_adjustment_id:data,evidence_attached:!!path},{status:201})}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params;const c=await ctx(id);if(c.error)return c.error;const b=await request.json().catch(()=>({}));if(!b.adjustment_id)return NextResponse.json({error:'adjustment_id is required'},{status:400});let data,error;if(b.action==='approve'){({data,error}=await c.s.rpc('approve_price_adjustment',{p_adjustment_id:b.adjustment_id}))}else if(b.action==='reject'){({data,error}=await c.s.rpc('reject_price_adjustment',{p_adjustment_id:b.adjustment_id}))}else return NextResponse.json({error:'Unsupported action'},{status:400});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({result:data})}